### ISSUE TITLE
Incorrect SHA checksum hashes

### ISSUE THREAD

**Issue by matsko** [jahed/node-terraform#15]
Hello.

I've run into an issue where I can't use your Terraform binary anymore since the checksum values you have in the `hashes.txt` file do not match what my system produces.

I was able to pull up this webpage: https://releases.hashicorp.com/terraform/1.3.7 and I can see that (for Mac OSX 64), the checksum value (both on the webpage and on my machine) get produced as `6cda396999c9a27cb90c4902913c10ac0afe1bfceb957ed50a4298c5872979cf`, however the hash value in this repo is `8860db524d1a51435cbed731902c7de1595348c09dd5b3a342024405c8e7ef74`.

I was able to pull up the `6cda...` checksum in three ways:
- By adding console logs in the `@jahed/terraform` source code and running node on the download
- By downloading terraform darwin 1.3.7 running (https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_darwin_arm64.zip) and then running `hasum -a 256` on the zip
- By looking at the checksum file in the releases website that I linked

All three are the same, yet the hashes.txt file is different.

How did you compute the hash values? I noticed that 1.3.5 and 1.3.6 are different as well.

Note that I am unable to use your plugin at all at the moment.

Thank you for maintaining and keeping this up to sync with each of the releases.

**Comment by matsko** [comment]
For the time being I've had to use a bash script to download Terraform directly and use that.

**Comment by jahed** [comment]
The hashes are from their website, they're pulled into the package at time of publishing to ensure if their website and signing keys gets compromised, it won't execute a potentially malicious binary.

https://github.com/jahed/node-terraform/blob/master/scripts/verify-version.sh
https://github.com/jahed/node-terraform/blob/master/hashes.txt

It looks like they recently re-published macOS binaries over the same version rather than issuing a new version. All the other platform hashes are the same. Can't say I agree with what they did and this doesn't seem to be documented anywhere so it's a bit suspicious.

I'll look into publishing a pre-release to workaround this and maybe add some monitoring to detect when this happens again.

**Comment by jahed** [comment]
Fixed in v1.3.7-0.1.0 and future Terraform releases. https://github.com/jahed/node-terraform/compare/v1.3.7...v1.3.7-0.1.0

Thanks for reporting this issue.
